sveltejs/rollup-plugin-svelte

.gitignore
.travis.yml
appveyor.yml
package-lock.json
package.json
rollup.config.js
src/index.js
test/node_modules/widget/package.json
test/node_modules/widget/src/Widget.html
test/node_modules/widgets/package.json
test/node_modules/widgets/src/Foo.html
test/test.js

This implements the first part of https://github.com/sveltejs/svelte/issues/604 — if a component has a `pkg.svelte` property or a `pkg['svelte.root']` property, this plugin will use that to locate the original uncompiled component, rather than the compiled distributable version.
Future work:
* put the resolution logic in a separate module so it can be used by other things like svelte-loader?
* Warn on version mismatches
* Respect `pkg.engines`

resolve using pkg.svelte and pkg.svelte.root

---

package-lock.json
package.json
src/index.js
test/sourcemap-test/index.html
test/sourcemap-test/src/Bar.html
test/sourcemap-test/src/Foo.html
test/sourcemap-test/src/main.js
test/test.js

Changes the first argument to the `css` callback to be an object with `code` and `map` properties, and a `write` method for convenience that generates a CSS file with an accompanying sourcemap:
```js
// rollup.config.js
export default {
entry: 'src/main.js',
dest: 'public/bundle.js',
format: 'iife',
plugins: [
svelte({
cascade: false,
css: css => {
css.write('public/bundle.css'); // generates bundle.css and bundle.css.map
}
})
]
};
```
The `write` method sets the `map.file` property correctly and makes the `sources` in the sourcemap relative to the output file, so it's recommended over handling the `code` and the `map` directly (though that's totally possible).
Attempting to use `css` directly in a string will invoke the `toString` method, which prints a deprecation warning before …

generate CSS sourcemaps

---

src/index.js

This adds support for specifying `shared` at build time, like the base svelte API.
All tests pass.

Added support for passing a custom `shared` file.

---

src/index.js
test/test.js

Once https://github.com/sveltejs/svelte/pull/987 lands this will make it so that `rollup-plugin-svelte` will pass the `id` to `svelte.preprocess()` as the `filename` param.
Implements the other part of what I was talking about in https://github.com/sveltejs/svelte/issues/983
The test will **fail** until https://github.com/sveltejs/svelte/pull/987 is merged & released, not much I can do about that beyond mocking out `svelte.preprocess()` which I'm happy to do if @Rich-Harris prefers.

feat: pass filename to svelte.preprocess

---

README.md

Seems that rollup has changed how it likes to be configured. Syntax from: https://rollupjs.org/guide/en#using-plugins

Error: you must specify format

---

package-lock.json
package.json
rollup.config.js
src/index.js

This allows other plugins to process and bundle styles, instead of requiring svelte to write them out itself.

Make svelte plugin emit styles as virtual files

---

package-lock.json
src/index.js
test/test.js

This fixes two issues:
- `emitCss` wasn't naming files correctly when using non-`html` extensions like `svelte`
- `emitCss` didn't properly escape the filenames when outputting the `import` lines
Partially fixes sveltejs/sapper-template#77

Fix `emitCss`

---

index.js
package-lock.json
package.json

This will replace the deprecated `ongenerate` hook with the `generateBundle` hook and use `this.warn` instead of `console.log` for warnings. Also updates some dependencies.

Prepare for rollup 1.0

---

index.js

To avoid deprecation warning in Rollup 1.0+
I don't know what version `this.addWatchFile` was added in, but it's not present in the earliest version of Rollup listed as a peer dependency of this plugin, so this change isn't assuming it's present. It falls back to the old behavior if it's not.

use this.addWatchFile when present

---

index.js

The current code is creating a new `object` from the passed `options.preprocess`, which turns an `array` of preprocessors into a plain `object`. That would be okay if it wasn't for [this line in the svelte compiler](https://github.com/sveltejs/svelte/blob/master/src/preprocess/index.ts#L80)
Closes #51 
I've also simplified the `dependency` collection since the `preprocess()` result should have the `dependencies` list.

Fix support for array of preprocessors

---

index.js
test/test.js

As discussed in https://github.com/sveltejs/svelte/issues/3804 and https://github.com/rollup/rollup-plugin-svelte/issues/74, I'm not entirely sure about the implications for backwards compatibility.
I've tried adhering to existing code style, but let me know if anything needs changing (or feel free to do so yourself).
Tests were failing because Node 6 doesn't support `async`/`await`, so I've tried fixing that in an additional commit - unsuccessfully, as it appears Svelte itself uses `async`/`await`. Since April 2019 marked the end of life for Node 6 LTS, should we use Node 8 in `.travis.yml` instead?

Avoid overriding Svelte 3's default name assignment

---

README.md

As per https://github.com/sveltejs/svelte/issues/4258 - Support hydrating head elements

Document hydratable attribute

---

package.json

The npm package is being published without "index.d.ts" file, so I added the missing file to files list.

add "index.d.ts" to publish files.

---

README.md

Removes unused import for `fs` in Readme example

Removes unused import in Readme example

---

index.js
test/node_modules/esm-component/package.json
test/node_modules/esm-component/src/Component.svelte
test/node_modules/esm-no-pkg-export/package.json
test/test.js

Fixes #104 
Alternative to to #108 #109 
This PR gathers all of these error together, ignoring duplicates, and reports them at the end with a helpful message. The other PRs were very noisy and resulted in many duplicates being posted to the console.

Handle missing export error

---

README.md
index.d.ts

As per [the docs](https://github.com/sveltejs/svelte/blob/master/site/content/docs/03-run-time.md#custom-element-api), the `customElement` option is exposed in the public API to compile Svelte components to custom elements. It should be properly typed.

add customElement typings

---

README.md
index.js
package-lock.json
package.json
test/test.js

Use this.emitFile to generate css files

---

index.d.ts

Hi there :wave:
I've noticed that while the `generate` option is documented in the plugin, it's not exposed in the Typescript's defintions.
I used the type from https://github.com/sveltejs/svelte/blob/d19bcef6901768844cc89cb39d29873381f9969a/src/compiler/interfaces.ts#L111
It would be possible to change the `Options` interface to extend the `CompileOptions` type from Svelte.
```diff
+import { CompileOptions } from "svelte/types/compiler/interfaces";
-interface Options {
+interface Options extends CompileOptions {
```
But it could be misleading since some options are fully handled by the plugin and can't be changed (`format`, `sveltePath`, `css`) and I'm not sure how well it would handle Svelte v2.
I'm definitely not a Typescript expert so I've used the safe way here!
Have a nice day!
PS: …

Fix types for generate option

---

index.d.ts
index.js

Initially just added types from #72; but then decided to extract an `emit` function to minimize potential misuse within the `css` function. AKA, by exposing the entire `PluginContext` within the `css` function, one could easily fumble around and break their Rollup build. By _just_ exposing `this.emit`, we still offer flexibility of emitting additional assets within the `css()` callback, if/when needed.

Refactor: CssWriter

---

index.d.ts

readme declares `css: false` but types disallowed it

fix(types): allow `css: false` option

---

index.js

See: https://github.com/sveltejs/rollup-plugin-svelte/issues/94#issuecomment-685255865
Fixes #94

Omit css-unused-selector when options.css is false, not true

---

index.d.ts
index.js

A lot of the examples omit the map parameter for the function in the css option. For example `css: css.write('bundle.css')`. When using typescript in the rollup config, this displays an error because the map parameter is required.
The write function seems to have a condition for explicit false values of the map parameter and for all other values it runs the else statement. By setting the map default value to true, it should behave exactly as before.
Also updated the typings to reflect this change.

Added default value to CssWriter.write map option

---

package-lock.json
package.json

* Require `rollup@2.x` and beyond from now on
* Require `svelte@3.5.0` and beyond from now on (https://github.com/sveltejs/rollup-plugin-svelte/pull/126#issuecomment-689580302)
And defines an `engines.node` requirement for the first time. We're matching Rollup 2.x's restriction – and Node 10+ allows us to start using `async`, if nothing else.
The primary purpose of this PR is maintainer health/sanity, because supporting multi-year-old versions "just because" is not sustainable. Semver allows us to safely move on by cutting a new major release. Users stuck on old versions can continue to use the old version of `rollup-plugin-svelte` & others.
In the short-term, this unblocks #126

breaking: version requirements

---

index.d.ts

Extends the `CompileOptions` directly, since everything gets passed into `svelte/compiler` anyway. Saves us from having an ongoing battle of "oh this is missing too", as we have.
This is separate to (and should land after) #125 
Verified that both PRs work together locally.

fix(types): extend `CompileOptions` interface directly

---

index.d.ts
index.js
test/index.js

It's really a few fixes, but it since it is a change in the default behavior, safer to just call this breaking.
Doing so means we can also allow #126 to land (re: compatibility concerns) and take this opportunity to finally (!) declare **useful** peer dependency constraints, including Rollup@2x. (Fixing those can be a separate PR) Edit: #138 
***Changes***
Our CSS Writer is broken. While it does work, it's not entirely useful given its environment. As of today (before this PR), the `CssWriter` class:
* Completely ignores [`output.assetFileNames`](https://rollupjs.org/guide/en/#outputassetfilenames), forcing `"bundle.css"` as your final output, even though all other assets/chunks will/are (likely) configured to have hashed filenames.
_To go back to previous behavior, in their Rollup …

breaking: Css Writer

---

index.js
test/index.js

Previously, a `assets/bundle.css` was including this:
```css
/*# sourceMappingURL=assets/bundle.css.map */
```
This resolved in an incorrect sourcemap since when resolved from `assets/bundle.css`, this would produce a request to `assets/assets/bundle.css.map`.
This was also true for the `"file"` key inside the sourcemap itself. 
Both locations now relatively-resolve to one another. AKA, if writing to an `assets` directory (Rollup default) then the output files will _not_ include the `assets/` prefix when referencing one another.

fix(css): link `sourcemap` with source correctly

---

index.js

My main motivation for this PR is that https://github.com/sveltejs/svelte/pull/4856 would embed the `filename` in the compiled code. I don't think that should be an absolute path because that makes it so that builds are not reproducible (e.g. compiled file will be different if you build in different directory or different machine), can leak information (e.g. my username is in my path), etc.
The `filename` is used in three existing places today:
* debug - I think relative path is easier to read for debugging and drops the redundant information
* sourcemap - the examples I see online use relative paths (e.g. [bugsnag article/tutorial](https://www.bugsnag.com/blog/source-maps)), so it seems like an improvement there
* passed to preprocess - I did an `npm link` of this PR against …

Make filename relative

---

index.d.ts
index.js
test/index.js

Addresses the `compilerOptions` synchronization step from #144 
Decided to kick the bucket on whether or not to auto-load `svelte.config.js` for another day.

break: use `compilerOptions` for `svelte.compile` config

---

CHANGELOG.md
index.js

Fixes second issue seen in https://github.com/sveltejs/svelte/issues/5659 where `svelte/compiler.js` didn't match anything in the exports map.

fix svelte/compiler import

---

README.md

chore: mention `resolve` plugin in readme

---

index.d.ts

This would not be necessary if we do https://github.com/sveltejs/rollup-plugin-svelte/pull/155. However, if we decide not to move forward with that then this PR would be a good cleanup

Remove unused code from type definitions

---

index.js
package-lock.json
package.json

This includes 2 major version bumps:
2-3: updates minimum rollup version to 1.20 and node version to 8, not a problem
3-4: fixes/changes behavior of createFilter with absolute paths or globs at start, see https://github.com/rollup/plugins/pull/517

break: update rollup-pluginutils to @rollup/pluginutils

---

index.js
package-lock.json
package.json

I'm not sure what the story is with #198 but it didn't work, because the `get_dir` function was called inside the `catch` block which defeats the object.
This PR takes a much simpler approach — it just walks up the tree looking for `node_modules/<name>/package.json`. Crude, but should work in all the cases we care about (it doesn't need to reimplement the entire Node module resolution algo, it just needs to find libraries with a `pkg.svelte`).
I assume we also need to respect the `svelte` export condition, but that seems like something that should happen separately.

fix package resolution

---

index.js
package-lock.json
package.json
test/index.js

We plan to release a version of `svelte-package` that encourages package authors to omit the `default` export condition. To resolve these packages, Rollup users are required to have `exportConditions: ['svelte']` in their `@rollup/plugin-node-resolve` config.
With this change, we can identify cases where the field is not configured, and print a loud warning that will hopefully allow people to self-diagnose resolution failures and fix them.

warn about missing svelte export condition

---

index.js

fix: pass options to silence warning

---

index.js

to remove below warning
```
compilerOptions.css as a boolean is deprecated. Use 'external' instead of false.
```
set css to 'external' while svelte version >= 4
latest [svelte compiler](https://svelte.dev/docs/svelte-compiler) has changed `css` option values to
```
css?: 'injected' | 'external' | 'none' | boolean;
```

feat: set compilerOptions.css to 'external' when emitCss was true
